[features]
seeds = false
skip-lint = false

[programs.localnet]
super_simple_randomness = "E5MAszjz8qZZDHKqQ21g5wYuhMTjMbk1L4L4jBFXMgqG"
switchboard_randomness_callback = "5bKuRru1qgEeQUXSAJvsXc8hZEGpCucEaaDQkmyd8j6v"
scheduled_lottery_request = "6AKXZiKbmj3D45bDZpa9fo6vUV4qGeeeRCZ5qRhE4Ve4"

[programs.devnet]
super_simple_randomness = "E5MAszjz8qZZDHKqQ21g5wYuhMTjMbk1L4L4jBFXMgqG"
switchboard_randomness_callback = "5bKuRru1qgEeQUXSAJvsXc8hZEGpCucEaaDQkmyd8j6v"
scheduled_lottery_request = "6AKXZiKbmj3D45bDZpa9fo6vUV4qGeeeRCZ5qRhE4Ve4"

[provider]
# cluster = "Localnet"
# wallet = "~/.config/solana/id.json"

cluster = "Devnet"
wallet = "~/switchboard_environments_v2/devnet/upgrade_authority/upgrade_authority.json"

# cluster = "Mainnet"
# wallet = "~/switchboard_environments_v2/mainnet/upgrade_authority/upgrade_authority.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"
superior-flip = "tsx ./scripts/superior-flip.ts"
update-measurement = "tsx ./scripts/update-measurement.ts"

[test.validator]
url = "https://api.devnet.solana.com"

[test]
startup_wait = 15000

[[test.validator.clone]] # sbv2 programID
address = "SW1TCH7qEPTdLsDHRgPuMQjbQxKdH2aBStViMFnt64f"

[[test.validator.clone]] # sbv2 IDL
address = "Fi8vncGpNKbq62gPo56G4toCehWNy77GgqGkTaAF5Lkk"

[[test.validator.clone]] # sbv2 SbState
address = "CyZuD7RPDcrqCGbNvLCyqk6Py9cEZTKmNKujfPi3ynDd"

[[test.validator.clone]] # sb attestation programID
address = "sbattyXrzedoNATfc4L31wC9Mhxsi1BmFhTiN8gDshx"

[[test.validator.clone]] # sb devnet attestation IDL
address = "5ExuoQR69trmKQfB95fDsUGsUrrChbGq9PFgt8qouncz"

[[test.validator.clone]] # sb devnet programState
address = "5MFs7RGTjLi1wtKNBFRtuLipCkkjs4YQwRRU9sjnbQbS"
